# Generated by Django 3.2 on 2021-10-27 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleOfContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Job')),
                ('company_name', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=19)),
                ('comments', models.TextField(blank=True, max_length=800, null=True)),
                ('motiv_letter', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Letter of Motivation')),
                ('cv', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='CV')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.categories', verbose_name='Category')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.status', verbose_name='Job Status')),
                ('style_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.styleofcontract', verbose_name='Job style')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.typeofcontract', verbose_name='Job type')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
