# Generated by Django 3.2 on 2021-09-27 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiv_letter', models.BinaryField(blank=True, null=True)),
                ('cv', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleOfContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=3, max_digits=19)),
                ('comments', models.TextField(blank=True, max_length=800, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.categories')),
                ('info_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsearch.infoupload')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.status')),
                ('style_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.styleofcontract')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.typeofcontract')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.status')),
            ],
        ),
    ]
