# Generated by Django 3.2 on 2021-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
