# Generated by Django 3.2 on 2021-11-01 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=19, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
