# Generated by Django 3.2 on 2021-10-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_alter_joboffer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='info_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsearch.infoupload'),
        ),
    ]
