# Generated by Django 3.2 on 2021-10-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0003_alter_joboffer_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotivLetterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiv_letter', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='info_id',
        ),
        migrations.DeleteModel(
            name='InfoUpload',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='cv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsearch.cvupload'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='motiv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsearch.motivletterupload'),
        ),
    ]
