# Generated by Django 3.2 on 2021-10-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0004_auto_20211011_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvupload',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='motivletterupload',
            name='motiv_letter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
