# Generated by Django 3.2 on 2021-10-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0005_auto_20211012_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvupload',
            name='cv',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='motivletterupload',
            name='motiv_letter',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
