# Generated by Django 3.2 on 2021-10-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0006_auto_20211012_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='cv_id',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='motiv_id',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='motiv_letter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CvUpload',
        ),
        migrations.DeleteModel(
            name='MotivLetterUpload',
        ),
    ]
