# Generated by Django 3.2 on 2021-10-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0007_auto_20211012_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='motiv_letter',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
