# Generated by Django 3.2 on 2021-10-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0008_auto_20211012_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='motiv_letter',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
