# Generated by Django 3.2 on 2021-10-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0009_auto_20211012_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewDate',
        ),
    ]
