# Generated by Django 3.2 on 2021-10-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0010_delete_interviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='motiv_letter',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Letter of Motivation'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.status', verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.styleofcontract', verbose_name='Job style'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearch.typeofcontract', verbose_name='Job type'),
        ),
    ]
